name: release
run-name: Release beancount-china-income-tax to PyPI
on:
  push:
    branches:
      - master
    paths:
      - pyproject.toml

  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for release'
        required: false
        default: 'Manual release'

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - uses: pdm-project/setup-pdm@v3

    - name: Publish package distributions to PyPI
      run: pdm publish